name: gastos_app
description: proyecto que permite rendir gastos para la empresa Transportes Ruiz.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.5
  firebase_auth: ^4.17.5
  firebase_core: ^2.25.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_login: ^5.0.0
  image_picker: ^1.0.7
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/images/
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
    
  
