// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXC_mIp9lcTFF8wYRUBTv2tDe6ABCMcYw',
    appId: '1:986908165462:web:df4a7102d00834dae982f7',
    messagingSenderId: '986908165462',
    projectId: 'gastosweb-c4e3c',
    authDomain: 'gastosweb-c4e3c.firebaseapp.com',
    storageBucket: 'gastosweb-c4e3c.appspot.com',
    measurementId: 'G-8E4R3M5WPF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnx0hdAioq9z-F0LnpURBqoTwIy7D1q2Q',
    appId: '1:986908165462:android:d20cfbe47aa88893e982f7',
    messagingSenderId: '986908165462',
    projectId: 'gastosweb-c4e3c',
    storageBucket: 'gastosweb-c4e3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUfqx2F6cvSRZlNOU2nowkBRDYVOepw-A',
    appId: '1:986908165462:ios:5506fe74d0f5783fe982f7',
    messagingSenderId: '986908165462',
    projectId: 'gastosweb-c4e3c',
    storageBucket: 'gastosweb-c4e3c.appspot.com',
    iosBundleId: 'com.example.gastosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUfqx2F6cvSRZlNOU2nowkBRDYVOepw-A',
    appId: '1:986908165462:ios:0de9efb956e3162ce982f7',
    messagingSenderId: '986908165462',
    projectId: 'gastosweb-c4e3c',
    storageBucket: 'gastosweb-c4e3c.appspot.com',
    iosBundleId: 'com.example.gastosApp.RunnerTests',
  );
}
